server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/devconnect
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
