spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/devconnect
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: workspace-service
server:
  port: 8082
